src/main/java/ik/am/jpetstore/domain/model/Cart.java
/*
 *    Copyright 2010-2013 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package ik.am.jpetstore.domain.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

/**
 * @author Eduardo Macarron
 */
public class Cart implements Serializable {

    private static final long serialVersionUID = 8329559983943337176L;

    private final Map<String, CartItem> itemMap = Collections
            .synchronizedMap(new HashMap<String, CartItem>());

    private final List<CartItem> itemList = new ArrayList<CartItem>();

    public Iterator<CartItem> getCartItems() {
        return itemList.iterator();
    }

    public List<CartItem> getCartItemList() {
        return itemList;
    }

    public int getNumberOfItems() {
        return itemList.size();
    }

    public Iterator<CartItem> getAllCartItems() {
        return itemList.iterator();
    }

    public boolean containsItemId(String itemId) {
        return itemMap.containsKey(itemId);
    }

    public void addItem(Item item, boolean isInStock) {
        CartItem cartItem = (CartItem) itemMap.get(item.getItemId());
        if (cartItem == null) {
            cartItem = new CartItem();
            cartItem.setItem(item);
            cartItem.setQuantity(0);
            cartItem.setInStock(isInStock);
            itemMap.put(item.getItemId(), cartItem);
            itemList.add(cartItem);
        }
        cartItem.incrementQuantity();
    }

    public Item removeItemById(String itemId) {
        CartItem cartItem = (CartItem) itemMap.remove(itemId);
        if (cartItem == null) {
            return null;
        } else {
            itemList.remove(cartItem);
            return cartItem.getItem();
        }
    }

    public void incrementQuantityByItemId(String itemId) {
        CartItem cartItem = (CartItem) itemMap.get(itemId);
        cartItem.incrementQuantity();
    }

    public void setQuantityByItemId(String itemId, int quantity) {
        CartItem cartItem = (CartItem) itemMap.get(itemId);
        cartItem.setQuantity(quantity);
    }

    public BigDecimal getSubTotal() {
        BigDecimal subTotal = new BigDecimal("0");
        Iterator<CartItem> items = getAllCartItems();
        while (items.hasNext()) {
            CartItem cartItem = (CartItem) items.next();
            Item item = cartItem.getItem();
            BigDecimal listPrice = item.getListPrice();
            BigDecimal quantity = new BigDecimal(String.valueOf(cartItem
                    .getQuantity()));
            subTotal = subTotal.add(listPrice.multiply(quantity));
        }
        return subTotal;
    }

}

src/main/java/ik/am/jpetstore/app/cart/CartController.java
package ik.am.jpetstore.app.cart;

import javax.inject.Inject;

import ik.am.jpetstore.domain.model.Cart;
import ik.am.jpetstore.domain.service.catalog.CatalogService;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
@RequestMapping("cart")
public class CartController {
    @Inject
    protected CartHelper cartHelper;

    @Inject
    protected CatalogService catalogService;

    @Inject
    protected Cart cart;

    @ModelAttribute
    public CartForm setUpForm() {
        return new CartForm();
    }

    @ModelAttribute
    public Cart getCart() {
        return cart;
    }

    @RequestMapping("viewCart")
    public String viewCart() {
        return "cart/Cart";
    }

    @RequestMapping("addItemToCart")
    public String addItemToCart(
            @RequestParam("workingItemId") String workingItemId) {
        cartHelper.addItemToCart(workingItemId, cart);
        return "redirect:/cart/viewCart";
    }

    @RequestMapping("updateCartQuantities")
    public String updateCartQuantities(CartForm cartForm, Model model) {
        cartHelper.updateCartQuantities(cartForm, cart);
        return "redirect:/cart/viewCart";
    }

    @RequestMapping("removeItemFromCart")
    public String removeItemFromCart(@RequestParam("cartItem") String cartItem) {
        cart.removeItemById(cartItem);
        return "redirect:/cart/viewCart";
    }

    @RequestMapping("checkOut")
    public String checkOut() {
        return "cart/Checkout";
    }

}

src/main/webapp/WEB-INF/views/cart/Cart.jsp
<%@ include file="../common/IncludeTop.jsp"%>

<div id="BackLink">
    <a href="${pageContext.request.contextPath}/catalog"> Return to
        Main Menu</a>
</div>

<div id="Catalog">

    <div id="Cart">

        <h2>Shopping Cart</h2>
        <form:form modelAttribute="cartForm"
            action="${pageContext.request.contextPath}/cart/updateCartQuantities">
            <table>
                <tr>
                    <th><b>Item ID</b></th>
                    <th><b>Product ID</b></th>
                    <th><b>Description</b></th>
                    <th><b>In Stock?</b></th>
                    <th><b>Quantity</b></th>
                    <th><b>List Price</b></th>
                    <th><b>Total Cost</b></th>
                    <th>&nbsp;</th>
                </tr>

                <c:if test="${actionBean.cart.numberOfItems == 0}">
                    <tr>
                        <td colspan="8"><b>Your cart is empty.</b></td>
                    </tr>
                </c:if>

                <c:forEach var="cartItem" items="${cart.cartItems}">
                    <tr>
                        <td><a
                            href="${pageContext.request.contextPath}/catalog/viewItem?itemId=${f:h(cartItem.item.itemId)}">
                                ${f:h(cartItem.item.itemId)}</a></td>
                        <td>${f:h(cartItem.item.product.productId)}</td>
                        <td>${f:h(cartItem.item.attribute1)}
                            ${f:h(cartItem.item.attribute2)}
                            ${f:h(cartItem.item.attribute3)}
                            ${f:h(cartItem.item.attribute4)}
                            ${f:h(cartItem.item.attribute5)}
                            ${f:h(cartItem.item.product.name)}</td>
                        <td>${f:h(cartItem.inStock)}</td>
                        <td><form:input
                                path="quantity[${f:h(cartItem.item.itemId)}]"
                                size="3"
                                value="${f:h(cartItem.quantity)}" /></td>
                        <td><fmt:formatNumber
                                value="${f:h(cartItem.item.listPrice)}"
                                pattern="$#,##0.00" /></td>
                        <td><fmt:formatNumber
                                value="${f:h(cartItem.total)}"
                                pattern="$#,##0.00" /></td>
                        <td><a
                            href="${pageContext.request.contextPath}/cart/removeItemFromCart?cartItem=${f:h(cartItem.item.itemId)}">Remove</a>
                        </td>
                    </tr>
                </c:forEach>
                <tr>
                    <td colspan="7">Sub Total: <fmt:formatNumber
                            value="${cart.subTotal}" pattern="$#,##0.00" />
                        <input type="submit" value="Update Cart" /></td>
                    <td>&nbsp;</td>
                </tr>
            </table>
        </form:form>
        <c:if test="${cart.numberOfItems > 0}">
            <a
                href="${pageContext.request.contextPath}/order/newOrderForm">Proceed
                to Checkout</a>
        </c:if>
    </div>

    <sec:authorize access="isAuthenticated()">
        <sec:authentication property="principal.account" var="account" />
        <div id="MyList">
            <c:if
                test="${account.listOption}">
                <%@ include file="IncludeMyList.jsp"%>
            </c:if>
        </div>
    </sec:authorize>

    <div id="Separator">&nbsp;</div>
</div>

<%@ include file="../common/IncludeBottom.jsp"%>

src/main/webapp/WEB-INF/views/cart/Checkout.jsp
<%@ include file="../common/IncludeTop.jsp"%>

<div id="BackLink">
    <a href="${pageContext.request.contextPath}/cart/viewCart">
        Return to Shopping Cart</a>
</div>

<div id="Catalog">
    <table>
        <tr>
            <td>
                <h2>Checkout Summary</h2>

                <table>

                    <tr>
                        <td><b>Item ID</b></td>
                        <td><b>Product ID</b></td>
                        <td><b>Description</b></td>
                        <td><b>In Stock?</b></td>
                        <td><b>Quantity</b></td>
                        <td><b>List Price</b></td>
                        <td><b>Total Cost</b></td>
                    </tr>

                    <c:forEach var="cartItem" items="${cart.cartItems}">
                        <tr>
                            <td><a
                                href="${pageContext.request.contextPath}/catalog/viewItem?itemId=${f:h(cartItem.item.itemId)}">
                                    ${f:h(cartItem.item.itemId)}</a></td>
                            <td>${f:h(cartItem.item.product.productId)}</td>
                            <td>${f:h(cartItem.item.attribute1)}
                                ${f:h(cartItem.item.attribute2)}
                                ${f:h(cartItem.item.attribute3)}
                                ${f:h(cartItem.item.attribute4)}
                                ${f:h(cartItem.item.attribute5)}
                                ${f:h(cartItem.item.product.name)}</td>
                            <td>${f:h(cartItem.inStock)}</td>
                            <td>${f:h(cartItem.quantity)}</td>
                            <td><fmt:formatNumber
                                    value="${f:h(cartItem.item.listPrice)}"
                                    pattern="$#,##0.00" /></td>
                            <td><fmt:formatNumber
                                    value="${f:h(cartItem.total)}"
                                    pattern="$#,##0.00" /></td>
                        </tr>
                    </c:forEach>
                    <tr>
                        <td colspan="7">Sub Total: <fmt:formatNumber
                                value="${f:h(cart.subTotal)}"
                                pattern="$#,##0.00" /></td>
                    </tr>
                </table>
            <td>&nbsp;</td>

        </tr>
    </table>

</div>

<%@ include file="../common/IncludeBottom.jsp"%>

src/main/webapp/WEB-INF/views/cart/IncludeMyList.jsp
<sec:authorize access="isAuthenticated()">
    <p>
        Pet Favorites <br /> Shop for more of your favorite pets here.
    </p>
    <ul>
        <sec:authentication property="principal.myList" var="products" />
        <c:forEach var="product" items="${products}">
            <li><a
                href="${pageContext.request.contextPath}/catalog/viewProduct?productId=${f:h(product.productId)}">
                    ${f:h(product.name)} </a>(${f:h(product.productId)})</li>
        </c:forEach>
    </ul>
</sec:authorize>